"""обновление столбца

Revision ID: 84525ad0a1f8
Revises: d0bf96e74ce4
Create Date: 2024-08-13 13:46:56.310921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84525ad0a1f8'
down_revision: Union[str, None] = 'd0bf96e74ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
