"""empty message

Revision ID: c5b14e089327
Revises: e37897c5f8e9
Create Date: 2024-12-31 11:47:55.348554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b14e089327'
down_revision: Union[str, None] = 'e37897c5f8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_info')
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('status', sa.String(), nullable=True))
    op.add_column('user', sa.Column('birth_date', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birth_date')
    op.drop_column('user', 'status')
    op.drop_column('user', 'bio')
    op.create_table('profile_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='profile_info_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_info_pkey')
    )
    # ### end Alembic commands ###
